import { BrowserModule } from "@angular/platform-browser";
import { NgModule } from "@angular/core";

import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";

//importing formsModule
import { FormsModule } from "@angular/forms";
//importing HttpClientModule
import { HttpClientModule } from "@angular/common/http";
import { CommonModule } from "@angular/common";
import { BrowserAnimationsModule } from "@angular/platform-browser/animations";

//importing toastr
import { ToastrModule, ToastContainerModule } from "ngx-toastr";

//importing ngbootstrap
import { NgbModule } from "@ng-bootstrap/ng-bootstrap";

//importing ngx-datatable
import { NgxDatatableModule } from "@swimlane/ngx-datatable";

import { NgxSpinnerModule } from "ngx-spinner";

//importing socila login
import { SocialLoginModule, AuthServiceConfig } from "angularx-social-login";
import { GoogleLoginProvider } from "angularx-social-login";

//local modules generated by the developer
import { HomeModule } from "./home/home.module";
import { SharedModule } from "./shared/shared.module";
import { UserModule } from "./user/user.module";
//importing services
import { AppService } from "./app.service";
import { SocketService } from "./socket.service";

let config = new AuthServiceConfig([
  {
    id: GoogleLoginProvider.PROVIDER_ID,
    provider: new GoogleLoginProvider(
      "19394797597-btfag72i88oidesh6aujhmr748i26qrb.apps.googleusercontent.com"
    ),
  },
]);
export function provideConfig() {
  return config;
}

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    AppRoutingModule,
    FormsModule,
    HttpClientModule,
    CommonModule,
    BrowserAnimationsModule,
    ToastrModule.forRoot(),
    ToastContainerModule,
    NgbModule,
    NgxDatatableModule,
    NgxSpinnerModule,
    SocialLoginModule,
    HomeModule,
    SharedModule,
    UserModule,
  ],
  providers: [
    AppService,
    SocketService,
    {
      provide: AuthServiceConfig,
      useFactory: provideConfig,
    },
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
